### ISSUE TITLE
Content-Type header being set to null causes TypeError

### ISSUE THREAD

**Issue by FilipFilipov** [ytilis/ngx-batch-requests#1]
The `setDetectedContentType()` method has the following code
`req.headers.set(CONTENT_TYPE, req.detectContentTypeHeader())`

In cases where the request is a GET or just has no body this will result in a Content-Type value of null, which will then cause an exception when calling `req.headers.keys()`
`TypeError: Cannot read property 'length' of null`

This is apparently [the expected behavior](https://github.com/angular/angular/issues/18743) from `HttpHeaders`, so maybe add a null check there.

**Comment by ytilis** [comment]
Sorry for the delay in getting back to this issue, I was out of the country.

Anyway, I'll try to fix this in the next week or two, as I should probably create some tests so handle conditions like this in the future. In the meantime, I welcome pull requests if you need a faster solution.

**Comment by ytilis** [comment]
This should be solved by #2 and should be available in v2.0.6 on npm
